# ~/.zprofile
# ~/.zshrc

# About work
if [ -f ~/.public_alias ]; then
  . ~/.public_alias
fi

if [ -f ~/.private_alias ]; then
  . ~/.private_alias
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/z/z.sh ] && source ~/z/z.sh

alias zshrc='vim ~/.zshrc'
alias sss='source ~/.zshrc'

# Useing direnv
eval "$(direnv hook zsh)"
# Useing anyenv
eval "$(anyenv init -)"

# Node.js install
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"

# ==> libpq
# libpq is keg-only, which means it was not symlinked into /usr/local,
# because conflicts with postgres formula.

# If you need to have libpq first in your PATH, run:
export PATH="/usr/local/opt/libpq/bin:$PATH"

# For compilers to find libpq you may need to set:
export LDFLAGS="-L/usr/local/opt/libpq/lib"
export CPPFLAGS="-I/usr/local/opt/libpq/include"

# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# ruby 3.2
export PATH="/usr/local/opt/ruby/bin:$PATH"
