[[plugins]]
repo = 'vim-scripts/Align'
hook_add = '''
  " https://teratail.com/questions/68916
  " <Space>w=を無効にすることで<Space>wを動作を早くしたい
  " <Space>w=の使い方もわからないので、一旦無効にした
  map <Nop>(<Plug>AM_w=) <Plug>AM_w=
'''
on_i = 1

# 複数ワードハイライト
[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
  nmap <Space>m <Plug>(quickhl-manual-this)
  xmap <Space>m <Plug>(quickhl-manual-this)
  nmap <Space>M <Plug>(quickhl-manual-reset)
  xmap <Space>M <Plug>(quickhl-manual-reset)
'''
on_map = ['<Plug>(quickhl-manual-this)']

# これもなくてならないPlugin: コメントアウト機能(gcc)
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <silent>gcc <Plug>(caw:hatpos:toggle)
  vmap <silent>gcc <Plug>(caw:hatpos:toggle)
'''
on_map = ['<Plug>(caw:hatpos:toggle)']

[[plugins]]
repo = 'kana/vim-altr'
hook_add = '''
  nmap <F3> <Plug>(altr-forward)
  nmap <F2> <Plug>(altr-back)

  " For ruby tdd
  " call altr#define('%.rb', 'spec/%_spec.rb')
  " For rails tdd
  " call altr#define('app/models/%.rb', 'spec/models/%_spec.rb', 'spec/factories/%s.rb')
  " call altr#define('app/controllers/%.rb', 'spec/controllers/%_spec.rb')
  " call altr#define('app/helpers/%.rb', 'spec/helpers/%_spec.rb')
'''
on_ft = ['ruby','eruby']

[[plugins]]
# repo = 'tpope/vim-rails'
repo = 'cuichangquan/vim-rails'
rev = 'release'
hook_add = '''
  let g:rails_app_root = substitute(system('git rev-parse --show-toplevel'), '\n', '', 'g')
  let g:routes_cache_file = g:rails_app_root . '/_routes.txt'
'''
on_ft = ['ruby','eruby']

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
  vmap gx <Plug>(openbrowser-smart-search)
'''
on_map = ['<Plug>(openbrowser-smart-search)']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tpope/vim-repeat'
on_i = 1

[[plugins]]
repo = 'elzr/vim-json'
on_i = 1

[[plugins]]
repo = "nvie/vim-flake8"
on_ft = 'python'

[[plugins]]
repo = "nathanaelkane/vim-indent-guides"
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1

  " TABキーを押した際にタブ文字の代わりにスペースを入れる
  set expandtab
  set tabstop=2
  set shiftwidth=2
'''
on_i = 1

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  " なくてはならない設定
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''
on_map = ['<Plug>(expand_region_expand)']

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_path = '.*'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  " If you want to start window resize mode by `Ctrl+T`
  let g:winresizer_start_key = '<C-T>'
'''
on_path = '.*'

[[plugins]]
repo = 'nanonanomachine/vim-redash'
depends = [ 'webapi-vim' ]
on_cmd = ['RedashDescribe', 'RedashExecute', 'RedashPost', 'RedashSetDataSource', 'RedashShowDataSources', 'RedashShowTables']

[[plugins]]
repo = "tpope/vim-dispatch"
on_cmd = ['Dispatch','Start','Focus']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['help', 'h']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_i = 1

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'
