[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haya14busa/dein-command.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# from: https://github.com/Shougo/dein.vim/issues/74
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0
hook_add = '''
  set rtp+=/usr/local/opt/fzf

  " set prefix
  "let g:fzf_command_prefix = 'FZF'

  " fzf layout
  let g:fzf_layout = { 'window': '-tabnew' }

  " Mapping selecting mappings
  nmap <leader><tab> <plug>(fzf-maps-n)

  " Insert mode completion
  imap <c-x><c-k> <plug>(fzf-complete-word)
  imap <c-x><c-f> <plug>(fzf-complete-path)
  imap <c-x><c-j> <plug>(fzf-complete-file-ag)
  imap <c-x><c-l> <plug>(fzf-complete-line)

  " Advanced customization using autoload functions
  inoremap <expr> <c-x><c-k> fzf#vim#complete#word({'left': '15%'})
'''

# BCommits などのコマンドを提供してくれる
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
